/*  =========================================================================
    rfc_hello_classes - private header file

    Copyright (c) the Authors
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
    =========================================================================
*/

#ifndef RFC_HELLO_CLASSES_H_INCLUDED
#define RFC_HELLO_CLASSES_H_INCLUDED

//  Platform definitions, must come first
#include "platform.h"

//  External API
#include "../include/rfc_hello.h"

//  Extra headers

//  Opaque class structures to allow forward references

//  Internal API


//  *** To avoid double-definitions, only define if building without draft ***
#ifndef RFC_HELLO_BUILD_DRAFT_API

//  Self test for private classes
RFC_HELLO_PRIVATE void
    rfc_hello_private_selftest (bool verbose, const char *subtest);

#endif // RFC_HELLO_BUILD_DRAFT_API

#endif
